---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run Tests
        run: |
          npm run test:ci
          npm run e2e:protractor
        env:
          CHROMEDRIVER_FILEPATH: /usr/local/share/chromedriver-linux64/chromedriver

    timeout-minutes: 10
